language: java
jdk: oraclejdk8
sudo: false
script: mvn clean verify
deploy:
  provider: releases
  api_key:
    secure: HlDxiRfUD5kMm3RfPNrtl/x6ScQNrfqSmk/KzjRYgv38jvjft82k8SP5VyWmZ4r+kcxgv1vslZrpYb3/8JGTmRwBp0jX/vJA+UCH+klrcaVB6bJxoFZSoLZChn7BvZs7oggGxD+vOWXdkCLoxWqv/fBiKLR9KTTNPb+98/RO/DwM2xSv6QPSPADGxt9hXDO9GZHjrTOX1pZvFckn0ax9t0a9JWk0nMK+2nAX+iZwJyMxCCyWqZ16Vku99wG2kD/PrElu6y6aRPn2NknS+XA88r5mNFG5ML8eC0RANaUVCEDmNFUUobGOekuU005wr2tGG1SoDiqREXY0wTfT8VYynuzzC5mexhaSqSOhbHBzzueZTEHgBMlUxi+jnCS0wsCzEwouvhuaFXykqdgT0RgAhf+snahu89XXHrVEPpOJWYxII1EmD8Zoulb3so6H+LzmlQCh1myTGQIx8AobmmrDSz3KFJ3HP3oxLLEbwr9+cXs/ml/KzRUrSRlZ8vwXSNaICHBawyRjxAdf0HE5dbRNIwL53N9EBBqy3PbBDHn8fukDouZWdbLagRm0Nc1s9XrnYj61aeKCDVYoJt2a+np7nHc9WhC+V2sPbdi+m8KWtMuUeqYDTU0xRWNDQQvMK4bahs8kJxJn0UFG5oTts9zosfitECtAOp5MBOhESu/c3rs=
  file: target/zookeeper-monitor-jar-with-dependencies.jar
  on:
    tags: true
    repo: changreytang/zookeeper-monitor
